optimizer:
  name: radam_lookahead
  lr: 0.0003  # 
  lookahead_sync_period: 6  # 
  lookahead_slow_step: 0.5  # 
  weight_decay: 0.0  # No weight decay 

training:
  seed: 42
  epochs: 1000  # Increased to 1000  (with early stopping)
  batch_size: 4096  # Increased to 4096  (reduce if OOM)
  sigma_reg_weight: 0.0  # Disabled
  early_stop:
    metric: r_auc_mse
    patience: 15  # Increased to 15 
    mode: min

logging:
  mlflow:
    enabled: false
    tracking_uri: null
  save.dir: experiments/runs
